package in.co.nmsworks.training.week2.day3;

public class Report {

    public String header(){

        return "header";
    }
    public String body(){
        return "body";
    }
    public String footer(){
        return "footer";
    }
    public String generate(){
        return "generate" + header() + body() + footer();
    }

}


































// Base class defining the structure of a report
//abstract class Report {
//
//    public String header() {
//        return "--- REPORT HEADER ---";
//    }
//
//    public String body() {
//        return "Generic report body content.";
//    }
//
//    public String footer() {
//        return "--- REPORT FOOTER ---";
//    }
//
//    // Template method that combines all sections into a single string
//    public final String generate() {
//        return header() + "\n" + body() + "\n" + footer();
//    }
//}
//
//// Child class specialized for Sales data
//class SalesReport extends Report {
//
//    @Override
//    public String header() {
//        return "========================================\n" +
//                "🔥 Q2 PERFORMANCE: GLOBAL SALES REPORT 🔥\n" +
//                "========================================";
//    }
//
//    @Override
//    public String body() {
//        return "📈 Total Revenue: $1,245,000\n" +
//                "🤝 New Customers Acquired: 1,420\n" +
//                "🏆 Top Performing Region: North America";
//    }
//
//    @Override
//    public String footer() {
//        return "Generated by: Sales Dept | Confidential | Page 1 of 1";
//    }
//}
//
//// Child class specialized for Inventory data
//class InventoryReport extends Report {
//
//    @Override
//    public String header() {
//        return "========================================\n" +
//                "📦 FULFILLMENT CENTER INVENTORY REPORT  \n" +
//                "========================================";
//    }
//
//    @Override
//    public String body() {
//        return "✅ Total SKUs in Stock: 8,450\n" +
//                "⚠️ Low Stock Alerts: 14 Items\n" +
//                "🛑 Out of Stock Items: 3 Items";
//    }
//
//    @Override
//    public String footer() {
//        return "Generated by: Logistics | Automated System | Page 1 of 1";
//    }
//}
//
//// Main class to execute and display the reports
//public class Main {
//    public static void main(String[] args) {
//        // Instantiate the specific reports
//        Report salesReport = new SalesReport();
//        Report inventoryReport = new InventoryReport();
//
//        // Display Sales Report
//        System.out.println(salesReport.generate());
//
//        System.out.println("\n\n"); // Formatting spaces
//
//        // Display Inventory Report
//        System.out.println(inventoryReport.generate());
//    }
//}
